<script lang="ts">
  import Header from "$lib/components/Header.svelte";
</script>

<Header />

<main class="pt-36 pb-0 font-sans text-navy">

  <!-- Hero -->
  <div class="py-16 md:py-20">
    <div class="px-6 md:px-16 lg:px-24 max-w-[1600px] mx-auto">
      <p class="text-xs tracking-widest uppercase text-gray-400 font-medium mb-6">Legal</p>
      <h1 class="text-4xl md:text-5xl lg:text-6xl font-light tracking-tight text-black leading-[1.15]">
        Terms of Use
      </h1>
    </div>
  </div>

  <!-- Content -->
  <div class="py-12 md:py-16 border-t border-gray-100">
    <div class="px-6 md:px-16 lg:px-24 max-w-[1600px] mx-auto">
      <div class="max-w-3xl">

        <div class="prose prose-lg prose-gray font-light leading-relaxed">

          <p class="text-gray-600 leading-relaxed mb-12">
            By visiting this website, you accept the following Terms of Use:
          </p>

          <!-- Use Limitation -->
          <div class="mb-12">
            <h2 class="text-xl font-medium text-navy mb-4">Use Limitation</h2>
            <p class="text-gray-600 leading-relaxed">
              The documents and content contained herein are for personal and non-commercial use. You may not reproduce, publish, modify, copy, distribute, or sell any information on this site without explicit consent from CG Operating Group.
            </p>
          </div>

          <!-- Third Party Links -->
          <div class="mb-12">
            <h2 class="text-xl font-medium text-navy mb-4">Third Party Links</h2>
            <p class="text-gray-600 leading-relaxed">
              This website may contain links to third party sites not under the control of CG Operating Group. CG Operating Group is not responsible for the content on such sites.
            </p>
          </div>

          <!-- Trademarks -->
          <div class="mb-12">
            <h2 class="text-xl font-medium text-navy mb-4">Trademarks</h2>
            <p class="text-gray-600 leading-relaxed">
              All third-party trademarks, logos, and brand names displayed on this site are the property of their respective owners. Use of these names, trademarks, and brands is for identification purposes only and does not imply endorsement, sponsorship, or a direct partnership with CG Operating Group.
            </p>
          </div>

          <!-- Content Disclaimer -->
          <div class="mb-12">
            <h2 class="text-xl font-medium text-navy mb-4">Content Disclaimer</h2>
            <p class="text-gray-600 leading-relaxed">
              CG Operating Group may update, change, or delete any posted content at any time and without prior notice. The content posted on this site is provided for informational purposes only and is not binding on CG Operating Group in any way except where specifically indicated. Certain visual content on this Service, including images and videos, may be generated by artificial intelligence or sourced from third parties for illustrative purposes. We make no representations or warranties, express or implied, regarding the source, authenticity, accuracy, or ownership of such content.
            </p>
          </div>

          <!-- Copyright -->
          <div class="mb-12">
            <h2 class="text-xl font-medium text-navy mb-4">Copyright</h2>
            <p class="text-gray-600 leading-relaxed">
              Copyright © 2025 CG Operating Group.
            </p>
          </div>

        </div>

      </div>
    </div>
  </div>

  <!-- Footer -->
  <footer class="bg-navy text-white">
    <div class="py-16 md:py-20">
      <div class="px-6 md:px-16 lg:px-24 max-w-[1600px] mx-auto">
        <div class="grid grid-cols-2 md:grid-cols-5 gap-10 md:gap-8">
          <div class="col-span-2 md:col-span-2">
            <img src="/logo-footer.svg" alt="CG Operating Group" class="h-10 brightness-0 invert" />
          </div>

          <div>
            <p class="text-xs tracking-wider text-white/40 mb-5">Navigate</p>
            <nav class="flex flex-col gap-2.5">
              <a href="/needs" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Your Needs</a>
              <a href="/impact" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Our Impact</a>
              <a href="/firm" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Our Firm</a>
            </nav>
          </div>

          <div>
            <p class="text-xs tracking-wider text-white/40 mb-5">Services</p>
            <nav class="flex flex-col gap-2.5">
              <a href="/needs?tab=manufacturing" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Manufacturing</a>
              <a href="/needs?tab=distribution" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Distribution</a>
            </nav>
          </div>

          <div>
            <p class="text-xs tracking-wider text-white/40 mb-5">Connect</p>
            <nav class="flex flex-col gap-2.5">
              <a href="/contact" class="text-sm text-white/70 hover:text-white transition-colors duration-150">Contact</a>
              <a href="https://x.com" class="text-sm text-white/70 hover:text-white transition-colors duration-150">X</a>
              <a href="https://linkedin.com" class="text-sm text-white/70 hover:text-white transition-colors duration-150">LinkedIn</a>
            </nav>
          </div>
        </div>
      </div>
    </div>

    <div class="py-5 border-t border-white/10">
      <div class="px-6 md:px-16 lg:px-24 max-w-[1600px] mx-auto">
        <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-3">
          <p class="text-xs text-white/40">© 2025 CG Operating Group</p>
          <div class="flex items-center gap-4">
            <a href="/privacy" class="text-xs text-white/40 hover:text-white/70 transition-colors duration-150">Privacy Policy</a>
            <a href="/terms" class="text-xs text-white/40 hover:text-white/70 transition-colors duration-150">Terms of Service</a>
          </div>
        </div>
      </div>
    </div>
  </footer>

</main>
